"""Parameter estimation, empirical datasets, identifiability, and MCMC sampling.

EVERY INFERENTIAL CONCLUSION IN THIS SUBPACKAGE IS CURRENTLY `Tier.VOID`, and every call
emits `provisional.ProvisionalResultWarning`. Two reasons, both recorded in the P0
register: the objective is a function of (K_d, E, D) only, so three of six parameter
directions are structurally flat (P0-5); and both datasets are synthetic (P0-6). The
computations are real and the arrays are plain; the conclusions are not available without
`.get(acknowledge_void=True)`. P3 and P4 are the fix.
"""
from .data import (
    ALL,
    equilibrium_crc_from_model,
    peak_crc_from_model,
    DEACTIVATION_BENCHMARK,
    DOSE_RESPONSE_BENCHMARK,
    HOLDOUT,
    JAHN1997_PEAK_CRC,
    MISSING_DATASETS,
    TRAIN,
    DataKind,
    Normalisation,
    DeactivationDataset,
    DoseResponseDataset,
    assert_real_data,
    holdout_guard,
)
from .identifiability import (
    EQUILIBRIUM_IDENTIFIABLE,
    IDENTIFIABLE_BOUNDS,
    HessianSpectrum,
    IdentifiabilityClass,
    ProfileResult,
    ProfileLikelihoodResult,
    compute_fisher_information_matrix,
    compute_kinetic_objective,
    compute_profile_likelihood,
    cost_hessian_and_spectrum,
    equilibrium_chi2_identifiable,
    equilibrium_dose_response_chi2,
    fit_identifiable,
    identifiability_report,
    invariance_report,
    profile_likelihood,
)
from .reparam import UNLOCKED_BY, IdentifiableParams
from .mcmc import (
    LOG10_BOUNDS,
    EnsembleRun,
    MCMCChainResult,
    integrated_autocorr_time,
    log_posterior_log10,
    log_prior_log10,
    run_ensemble_mcmc,
    sample_ensemble,
    split_rhat,
)
from .likelihood import (
    DatasetFit,
    LikelihoodResult,
    MLEResult,
    concentrated_log_likelihood,
    fit_mle,
    fit_mle_vector,
    make_log_likelihood,
    score_holdout,
)
from .comparison import (
    FIT_CONVENTIONS,
    MODEL_SPECS,
    ComparisonResult,
    CVScore,
    CVVerdict,
    ModelFit,
    ModelSpec,
    RecoveryCheck,
    blocked_cv,
    compare_models,
    comparison_report,
    fit_one,
    recovery_check,
    resolve_cv,
)
from .posterior import (
    AgreementResult,
    PosteriorResult,
    agreement_with_profiles,
    posterior_report,
    sample_identifiable_posterior,
    sample_posterior_vector,
    save_chain,
)

__all__ = [
    # data
    "ALL",
    "DOSE_RESPONSE_BENCHMARK",
    "DEACTIVATION_BENCHMARK",
    "TRAIN",
    "HOLDOUT",
    "JAHN1997_PEAK_CRC",
    "MISSING_DATASETS",
    "DataKind",
    "Normalisation",
    "DoseResponseDataset",
    "DeactivationDataset",
    "assert_real_data",
    "holdout_guard",
    "equilibrium_crc_from_model",
    "peak_crc_from_model",
    # identifiability
    "equilibrium_dose_response_chi2",
    "compute_kinetic_objective",
    "ProfileLikelihoodResult",
    "compute_profile_likelihood",
    "HessianSpectrum",
    "cost_hessian_and_spectrum",
    "compute_fisher_information_matrix",
    "invariance_report",
    # P3: the analysis on the parameters the data can determine
    "EQUILIBRIUM_IDENTIFIABLE",
    "IDENTIFIABLE_BOUNDS",
    "IdentifiabilityClass",
    "IdentifiableParams",
    "ProfileResult",
    "UNLOCKED_BY",
    "equilibrium_chi2_identifiable",
    "fit_identifiable",
    "profile_likelihood",
    "identifiability_report",
    # mcmc
    "LOG10_BOUNDS",
    "MCMCChainResult",
    "run_ensemble_mcmc",
    "log_prior_log10",
    "log_posterior_log10",
    "integrated_autocorr_time",
    "split_rhat",
    "sample_ensemble",
    "EnsembleRun",
    # P4: the likelihood each dataset is scored on its own observable against
    "DatasetFit",
    "LikelihoodResult",
    "MLEResult",
    "concentrated_log_likelihood",
    "make_log_likelihood",
    "score_holdout",
    "fit_mle",
    "fit_mle_vector",
    # P4: the posterior over the combinations the data can determine
    "PosteriorResult",
    "AgreementResult",
    "sample_identifiable_posterior",
    "sample_posterior_vector",
    "agreement_with_profiles",
    "posterior_report",
    "save_chain",
    # P5: model comparison
    "MODEL_SPECS",
    "FIT_CONVENTIONS",
    "ModelSpec",
    "ModelFit",
    "CVScore",
    "CVVerdict",
    "ComparisonResult",
    "RecoveryCheck",
    "fit_one",
    "blocked_cv",
    "resolve_cv",
    "compare_models",
    "comparison_report",
    "recovery_check",
]
