"""Benchmark datasets. Two are currently SYNTHETIC -- generated from a formula for
mechanics testing, not measured. See `synthetic` and `origin` on each, and roadmap P1-2
for the digitisation that replaces them.

WHAT WENT WRONG HERE, recorded because the defect is subtle and was shipped three commits
after the audit that should have prevented it (roadmap P0-6):

`DEACTIVATION_BENCHMARK` is `0.70*exp(-t/15) + 0.30*exp(-t/70)`, a formula, and it carried
`citation="Haas & Macdonald 1999 ..."`. `knowledge/07-paper-review.md` records that paper
as measuring **76.1 ms** for this quantity -- it is one of the six load-bearing citations
that claim-support audit found did not support the number attached to them. So the
generated trace's dominant 15 ms component was attributed to a paper that measured
something five times slower.

`DOSE_RESPONSE_BENCHMARK` has the same problem in a subtler form: its plateau is exactly
0.750, which is `gabaa_kinetics.FIT_TARGETS["po_max"]` -- the model's own fit target. So
"fitting the model to the data" was partly circular, and its `sem` values have no stated
origin at all.

THE FIX IS NOT A RENAME. Both datasets keep their names and stay usable, so no caller
breaks and the mechanics tests still have something to run against. What changed is that

  * `synthetic=True` and `origin` say what they are, in the object itself;
  * the citation text survives under `motivated_by`, a field whose name cannot be mistaken
    for provenance, while `source_key` stays empty;
  * `assert_real_data()` makes any fit that consumes them warn and taint its conclusions
    automatically -- so when P1-2 lands real digitisations the flag flips to False, the
    warning stops on its own, and no call site changes.

A synthetic trace may exist and may be used. It may never carry provenance it does not
have, and it may never be the basis of a claim about receptors (roadmap §5.4).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, Sequence

import numpy as np

from ..models.base import Observable


@dataclass(frozen=True)
class DoseResponseDataset:
    """Concentration-response measurements, or a synthetic stand-in for them."""

    citation_label: str          # display text only; see `source_key` for provenance
    preparation: str
    concs_um: np.ndarray
    mean_response: np.ndarray
    sem: np.ndarray
    observable: Observable = Observable.PEAK
    #: True = generated by a formula rather than measured. Taints any fit that uses it.
    synthetic: bool = False
    #: For a synthetic dataset: the exact expression and why it exists.
    origin: str = ""
    #: A paper that INSPIRED the shape. NOT provenance. Never set this for real data --
    #: real data gets `source_key`.
    motivated_by: str = ""
    #: A key into `provenance`. Set ONLY for genuinely digitised or published data.
    source_key: str = ""
    #: Figure/table the numbers came from, e.g. "Fig 2B, filled circles".
    figure: str = ""
    #: Tool, method, date and who, for a real digitisation.
    digitisation: str = ""
    n_cells: int | None = None
    role: Literal["train", "holdout"] = "train"

    def __post_init__(self):
        _validate_dataset(self)

    @property
    def key(self) -> str:
        return self.citation_label


@dataclass(frozen=True)
class DeactivationDataset:
    """A macroscopic deactivation current trace, or a synthetic stand-in for one."""

    citation_label: str
    pulse_duration_ms: float
    gaba_conc_um: float
    time_ms: np.ndarray
    normalized_current: np.ndarray
    observable: Observable = Observable.CHARGE
    synthetic: bool = False
    origin: str = ""
    motivated_by: str = ""
    source_key: str = ""
    figure: str = ""
    digitisation: str = ""
    n_cells: int | None = None
    role: Literal["train", "holdout"] = "train"

    def __post_init__(self):
        _validate_dataset(self)

    @property
    def key(self) -> str:
        return self.citation_label


def _validate_dataset(ds) -> None:
    """A dataset cannot be both generated and sourced, and must say which it is."""
    if ds.synthetic:
        if not ds.origin.strip():
            raise ValueError(
                f"{ds.citation_label!r} is marked synthetic but has no `origin`. State the "
                f"expression that generated it and why it exists, or it is indistinguishable "
                f"from data.")
        if ds.source_key:
            raise ValueError(
                f"{ds.citation_label!r} is marked synthetic AND carries source_key="
                f"{ds.source_key!r}. A generated trace has no provenance; put the paper that "
                f"inspired it in `motivated_by`.")
    else:
        if not ds.source_key:
            raise ValueError(
                f"{ds.citation_label!r} claims to be real data (synthetic=False) but names "
                f"no `source_key`. Register it in `provenance` first; roadmap §2.2.")
        if not ds.figure.strip() or not ds.digitisation.strip():
            raise ValueError(
                f"{ds.citation_label!r} is real data but does not say which `figure` it came "
                f"from or how it was obtained (`digitisation`). Roadmap P1-2 requires both.")


# ---------------------------------------------------------------------------------------
# 1. Concentration-response, PEAK observable.
#
# SYNTHETIC. Shaped to resemble a published alpha1beta2gamma2 macroscopic peak-current
# curve (EC50 ~20-30 uM, Hill ~1.3-1.5) but generated, not digitised. Its plateau is
# exactly the project's own po_max fit target, which is why a fit against it is partly
# circular -- see the module docstring.
# ---------------------------------------------------------------------------------------
_CONCS = np.array([0.3, 1.0, 3.0, 10.0, 30.0, 100.0, 300.0, 1000.0, 3000.0], dtype=float)
_RESP = np.array([0.005, 0.021, 0.075, 0.245, 0.540, 0.710, 0.745, 0.750, 0.750],
                 dtype=float)
_SEM = np.array([0.002, 0.005, 0.012, 0.025, 0.030, 0.020, 0.015, 0.010, 0.010],
                dtype=float)

DOSE_RESPONSE_BENCHMARK = DoseResponseDataset(
    citation_label="synthetic alpha1beta2gamma2 peak concentration-response",
    preparation="nominally recombinant alpha1beta2gamma2, whole-cell; NOT a real recording",
    concs_um=_CONCS,
    mean_response=_RESP,
    sem=_SEM,
    observable=Observable.PEAK,
    synthetic=True,
    origin=("hand-written response and SEM arrays shaped to resemble a sigmoid with "
            "EC50 ~20-30 uM and a 0.750 plateau. The plateau is exactly "
            "gabaa_kinetics.FIT_TARGETS['po_max'], so fitting the model to this curve is "
            "partly circular; the SEM values have no origin at all. Exists so the "
            "likelihood and identifiability machinery can be exercised before P1-2 "
            "supplies a digitisation."),
    motivated_by=("Mortensen et al. 2012 (J Physiol 590:69-78) and Sigel & Steinmann 2012 "
                  "report curves of this general shape. NEITHER was digitised and neither "
                  "supports these specific numbers."),
)

# ---------------------------------------------------------------------------------------
# 2. Macroscopic deactivation trace, CHARGE observable.
#
# SYNTHETIC, and the one that carried a mis-citation. See the module docstring.
# ---------------------------------------------------------------------------------------
_T_DEACT = np.linspace(0.0, 100.0, 50, dtype=float)
_I_DEACT = 0.70 * np.exp(-_T_DEACT / 15.0) + 0.30 * np.exp(-_T_DEACT / 70.0)

DEACTIVATION_BENCHMARK = DeactivationDataset(
    citation_label="synthetic biexponential deactivation trace",
    pulse_duration_ms=1.0,
    gaba_conc_um=1000.0,
    time_ms=_T_DEACT,
    normalized_current=_I_DEACT,
    observable=Observable.CHARGE,
    synthetic=True,
    origin=("0.70*exp(-t/15) + 0.30*exp(-t/70), evaluated on 50 points over 100 ms. A "
            "formula, not a digitisation. Exists so the kinetic-timescale half of the "
            "likelihood can be exercised before P1-2; it cannot make any rate "
            "identifiable in a way that means anything, because the timescales in it were "
            "chosen rather than measured."),
    motivated_by=("Haas & Macdonald 1999 (J Physiol 514:27-45) and Jones & Westbrook 1995 "
                  "measure macroscopic deactivation. IMPORTANT: "
                  "knowledge/07-paper-review.md records Haas & Macdonald 1999 as measuring "
                  "76.1 ms for this quantity, so the 15 ms component above is NOT that "
                  "paper's number and must not be attributed to it."),
)


#: Every registered dataset, for the provenance test to iterate.
ALL: dict[str, object] = {
    "dose_response_peak": DOSE_RESPONSE_BENCHMARK,
    "deactivation_charge": DEACTIVATION_BENCHMARK,
}

TRAIN = tuple(d for d in ALL.values() if getattr(d, "role", "train") == "train")
HOLDOUT = tuple(d for d in ALL.values() if getattr(d, "role", "train") == "holdout")


def assert_real_data(datasets: Sequence[object], *, caller: str) -> list[str]:
    """Warn, loudly and by name, for every synthetic dataset a fit is about to consume.

    Returns the list of synthetic dataset labels, so the caller can decide what to taint.
    A helper rather than a copied five-line block, because "forgot it in one of five
    places" is this project's recurring error E12 (roadmap §5.3).
    """
    from ..provisional import warn_provisional

    fake = [getattr(d, "citation_label", repr(d)) for d in datasets
            if getattr(d, "synthetic", False)]
    if fake:
        warn_provisional(
            what=f"{caller} (fitting against {len(fake)} synthetic dataset(s))",
            defect=("the following datasets are generated from formulae, not measured: "
                    + "; ".join(fake)
                    + ". A fit against them measures the formula, not a receptor."),
            register_item="P0-6 / P1-2",
            promote_by=("digitise the concentration-response and deactivation curves from "
                        "named published figures, register them in provenance.py, and set "
                        "synthetic=False -- this warning then stops on its own"),
        )
    return fake


def holdout_guard(datasets: Sequence[object], *, caller: str) -> None:
    """Refuse to fit against a held-out dataset.

    P5's cross-validation and P6's falsification both consume the holdout, and a fit that
    has seen it makes both meaningless. Enforced here rather than remembered.
    """
    leaked = [getattr(d, "citation_label", repr(d)) for d in datasets
              if getattr(d, "role", "train") == "holdout"]
    if leaked:
        raise ValueError(
            f"{caller} was passed held-out dataset(s) {leaked}. The holdout exists so P5 "
            f"can score out-of-sample and P6 can state a falsification bound; fitting "
            f"against it destroys both. Pass `fitting.data.TRAIN`.")
